hydra:
  job:
    chdir: false

defaults:
  - _self_
  - hyperparameters: hyperparameters_config
  - data: data_config
  - model: model_config

disable_warnings:
  - "OCCURRENCE_WARNING"
  - "CONFIG_WARNING"
