name: Run Test Dataloading

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  schedule:
    - cron: "0 13 * * 1"  # run every Monday at 13:00 UTC

jobs:
    build:
  
      runs-on: ubuntu-latest
  
      steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'  # Specify the Python version
  
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          # If you have other dependencies, install them here
  
      - name: Run pytest
        run: pytest tests/test_dataloading.py  # Runs pytest on your test file