name: Run Test Model

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  schedule:
    - cron: "0 13 * * 1"  # run every Monday at 13:00 UTC

jobs:
    build:
  
      runs-on: ubuntu-latest
      timeout-minutes: 30
  
      steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'  # Specify the Python version
  
      - name: Install Dependencies w/ requirements.txt
        run: |
          pip install -r requirements.txt
          # If you have other dependencies, install them here   

      - name: Run Pytest
        run: pytest tests/test_model.py