name: Run Test Dataloading

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  schedule:
    - cron: "0 13 * * 1"  # run every Monday at 13:00 UTC

jobs:
    build:
  
      runs-on: ubuntu-latest
  
      steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'  # Specify the Python version
  
      - name: Install Dependencies w/ requirements.txt
        run: |
          pip install -r requirements.txt
          # If you have other dependencies, install them here
    
      - name: DVC to get raw data
        run: |
         dvc remote add -f -d storage gs://mlops-data-dog/
         dvc pull
         python ./src/data/make_dataset.py --dataset complete    

      - name: Run Pytest
        run: pytest tests/test_dataloading.py